include:
  - path:
    - memphis.compose.yml
    - clickhouse.compose.yml
    - tsdb.compose.yml
    - temporal.compose.yml

services:
  api_service:
    build:
      context: .
      dockerfile: ./api_service.dockerfile
    image: bond-trading/api_service:latest
    container_name: api_service
    hostname: api_service
    depends_on:
      - memphis
    ports:
      - 8080:8080
    networks:
      - clickhouse
      - timescaledb
      - memphis
      - temporal
      - backend

  order_service:
    build:
      context: .
      dockerfile: ./order_service.dockerfile
    image: bond-trading/order_service:latest
    container_name: order_service
    hostname: order_service
    depends_on:
      - memphis
    ports:
      - 8081:8081
    networks:
      - clickhouse
      - timescaledb
      - memphis
      - temporal
      - backend

networks:
  backend:
    ipam:
      driver: default
