include:
  - path:
    - memphis.compose.yml
    - timescaledb.compose.yml

services:
  order-service:
    build:
      context: ../
      dockerfile: ./docker/order_service.dockerfile
    image: bond-trading/order-service:latest
    container_name: order-service
    hostname: order-service
    depends_on:
      memphis:
        condition: service_started
      memphis-metadata:
        condition: service_started
      memphis-rest-gateway:
        condition: service_started
      timescaledb:
        condition: service_started
    networks:
      - bond-trading
    ports:
      - 8081:8081

  api-service:
    build:
      context: ../
      dockerfile: ./docker/api_service.dockerfile
    image: bond-trading/api-service:latest
    container_name: api-service
    hostname: api-service
    depends_on:
      order-service:
        condition: service_started
    networks:
      - bond-trading
    ports:
      - 8080:8080
