include:
  - path:
    - memphis.compose.yml
    - timescaledb.compose.yml

services:
  order_service:
    build:
      context: ../
      dockerfile: ./docker/order_service.dockerfile
    image: bond-trading/order_service:latest
    container_name: order_service
    hostname: order_service
    depends_on:
      memphis:
        condition: service_started
      memphis-metadata:
        condition: service_started
      memphis-rest-gateway:
        condition: service_started
      timescaledb:
        condition: service_started
    ports:
      - 8081:8081
    networks:
      - memphis
      - timescaledb
      - backend

  api_service:
    build:
      context: ../
      dockerfile: ./docker/api_service.dockerfile
    image: bond-trading/api_service:latest
    container_name: api_service
    hostname: api_service
    depends_on:
      order_service:
        condition: service_started
    ports:
      - 8080:8080
    networks:
      - memphis
      - timescaledb
      - backend

networks:
  backend:
    ipam:
      driver: default
