include:
  - path:
    - memphis.compose.yml
    # - clickhouse.compose.yml
    - timescaledb.compose.yml

services:
  api_service:
    build:
      context: ../
      dockerfile: ./docker/api_service.dockerfile
    image: bond-trading/api_service:latest
    container_name: api_service
    hostname: api_service
    depends_on:
      - memphis
    ports:
      - 8080:8080
    networks:
      # - clickhouse
      - timescaledb
      - memphis
      - backend

  order_service:
    build:
      context: ../
      dockerfile: ./docker/order_service.dockerfile
    image: bond-trading/order_service:latest
    container_name: order_service
    hostname: order_service
    depends_on:
      - memphis
    ports:
      - 8081:8081
    networks:
      # - clickhouse
      - timescaledb
      - memphis
      - backend

networks:
  backend:
    ipam:
      driver: default
