include:
  - path:
    - networks.compose.yml

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    hostname: timescaledb
    restart: on-failure
    pull_policy: always
    networks:
      - bond-trading
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust  # disable password authentication
